import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sudharshan' at '8/16/17 10:52 PM' with Gradle 3.0
 *
 * @author sudharshan, @date 8/16/17 10:52 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       
        assertTrue(true);
    }
}
